[target.aarch64-linux-android]
ar = "/home/v/Android/Sdk/ndk/28.0.12433566/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar"
linker = "/home/v/Android/Sdk/ndk/28.0.12433566/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang"
# rustflags = [
#     "-L", "/path/to/ndk/platforms/android-29/arch-arm64/usr/lib",
#     "-lsqlite3",
# ]

[target.x86_64-linux-android]
ar = "/home/v/Android/Sdk/ndk/28.0.12433566/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar"
linker = "/home/v/Android/Sdk/ndk/28.0.12433566/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang"
rustflags = ["-C", "link-arg=/usr/lib/gcc/x86_64-redhat-linux/14/libgcc.a"]
